### ISSUE TITLE
自定义词库处理问题：这是一个Bug吗？

### ISSUE THREAD

**Issue by syncml** [shibing624/xmnlp#2]
我新增一个自定义字典
CustomDictionary2.txt：
黄色 bad 1000
av bad 1000
法轮功 bad 1000

```
        String text = "我是一个java程序员，他有一部AV黄色小电影，还是一个法轮功疯子";  // 怎么可能噗哈哈！
        System.out.println(Xmnlp.segment(text));
```

出来的结果是：
[我/rr, 是/vshi, 一个/mq, java/nx, 程序员/nnt, ，/w, 他/rr, 有/vyou, 一/m, 部/q, AV/nx, 黄色/bad, 小/a, 电影/n, ，/w, 还是/c, 一个/mq, 法轮功/n, 疯子/n]

法轮功的词性这么不是bad呢？

**Comment by shibing624** [comment]
不是bug，自定义词库“data/dictionary/custom/现代汉语补充词库.txt”中有：法轮功	n	61，这个是内置的自定义词，你可以删除或者替换即可。见更新后的示例DemoCustomDictionary。

**Comment by syncml** [comment]
对的，我后来把自定义的词典放在现代汉语补充词库.txt后面就好了，应该是先后次序的关系
